<a href="https://colab.research.google.com/github/kanishqdhangar/machine-learning/blob/main/sk-learn/sk_learn_StandardScaler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/Social_Network_Ads.csv")
df.head(1)

    User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0

In [ ]:
df=df.drop('User ID', axis=1, inplace=True)

In [ ]:
df=pd.read_csv("/content/Social_Network_Ads.csv")
df = df.drop('User ID', axis=1)
df.head(1)

  Gender  Age  EstimatedSalary  Purchased
0   Male   19            19000          0

In [ ]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female':0})

In [ ]:
from sklearn.model_selection import train_test_split
x=df.drop('Purchased', axis=1)
y=df['Purchased']
x_train,x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
x_train=pd.DataFrame(data=scaler.fit_transform(x_train), columns=x_train.columns)
x_test=pd.DataFrame(data=scaler.transform(x_test), columns=x_test.columns)
x_train.head(5)

   Gender       Age  EstimatedSalary
0    -1.0 -1.066752        -0.386344
1     1.0  0.797535        -1.229939
2    -1.0  0.110692         1.853544
3    -1.0  0.601294        -0.909955
4    -1.0  1.876859        -1.288118