<a href="https://colab.research.google.com/github/kanishqdhangar/machine-learning/blob/main/pandas/pandas-2-fortune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
company=pd.read_csv('/content/Fortune 500 Companies US.csv', encoding='latin-1')

In [ ]:
company.head(2)

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"

In [ ]:
type(company.groupby('Number of Employees'))

pandas.core.groupby.generic.DataFrameGroupBy

In [ ]:
sector=company.groupby('Number of Employees')

In [ ]:
sector.groups

{'1,00,300': [63], '1,03,500': [138], '1,05,000': [35], '1,06,000': [46, 220], '1,08,000': [129], '1,10,000': [197, 499], '1,14,000': [27, 81], '1,16,000': [2], '1,16,050': [135], '1,16,475': [133], '1,21,000': [127], '1,22,300': [66], '1,25,000': [71], '1,26,400': [34], '1,31,000': [72], '1,326': [479], '1,33,600': [161], '1,35,000': [177], '1,36,000': [80], '1,38,000': [40, 151], '1,40,000': [126], '1,464': [188], '1,48,300': [109], '1,48,400': [150], '1,50,540': [23], '1,50,942': [384], '1,59,000': [30], '1,60,900': [13], '1,69,000': [240], '1,72,000': [15], '1,770': [333], '1,91,000': [84], '1,95,000': [51, 58], '1,970': [401], '10,000': [208, 271], '10,212': [125], '10,299': [386], '10,400': [340], '10,471': [314], '10,700': [477], '10,900': [459], '11,000': [277, 455, 464], '11,121': [214], '11,170': [317], '11,300': [336], '11,320': [64], '11,476': [255], '11,500': [329, 349], '11,737': [76], '11,781': [485], '11,800': [447], '11,870': [484], '11,900': [266, 468], '12,030': [467], '12,157': [92], '12,380': [306], '12,390': [234], '12,438': [327], '12,500': [451], '12,600': [309, 335], '12,689': [364], '12,997': [79], '13,000': [170, 254, 261], '13,065': [307], '13,105': [456], '13,195': [238], '13,300': [114], '13,309': [221], '13,500': [260], '13,513': [262], '13,800': [424], '14,000': [299, 308, 363, 420, 432, 449], '14,125': [211], '14,200': [186], '14,400': [392], '14,500': [319], '14,700': [169, 360], '14,800': [33], '14,854': [226], '14,960': [233], '15,000': [184, 288], '15,549': [276], '15,700': [478], '15,706': [442], '15,707': [195], '15,800': [212], '15,986': [402], '16,000': [185, 428, 457], '16,021': [417], '16,027': [426], '16,150': [264], '16,200': [237, 356], '16,400': [492], '16,487': [454], '16,500': [338], '16,575': [279], '16,900': [152], '17,000': [350, 377, 488], '17,048': [97], '17,140': [368], ...}

In [ ]:
sector.sum()

,Rank,Company Name,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
Number of Employees,,,,,,,,,
"1,00,300",64,Coca-Cola,62.0,"$41,863",-5.5%,"$6,527.0",-11.2%,"$87,270","$1,82,153"
"1,03,500",139,Emerson Electric,128.0,"$20,268",-9.1%,"$1,635.0",-39.7%,"$21,743","$38,614"
"1,05,000",36,Procter & Gamble,34.0,"$71,726",-8.9%,"$10,508.0",49.3%,"$1,27,136","$2,29,700"
"1,06,000",268,IntelJ.C. Penney,279.0,"$59,387$12,547",7.3%-0.6%,"$10,316.0$1.0",-9.7%-,"$1,13,327$9,314","$1,70,539$1,901"
"1,08,000",130,Community Health Systems,125.0,"$21,374",-5.8%,"-$1,721.0",-,"$21,944","$1,010"
...,...,...,...,...,...,...,...,...,...
"93,000",137,Whirlpool,134.0,"$20,718",-0.8%,$888.0,13.4%,"$19,153","$12,762"
"95,400",74,Caterpillar,59.0,"$38,537",-18.0%,-$67.0,-103.2%,"$74,704","$54,402"
"96,500",54,Pfizer,55.0,"$52,824",8.1%,"$7,215.0",3.7%,"$1,71,615","$2,03,725"
"97,000",56,Lockheed Martin,60.0,"$50,658",9.8%,"$5,302.0",47.1%,"$47,806","$77,557"
"98,800",90,General Dynamics,88.0,"$31,353",-0.4%,"$2,955.0",-0.3%,"$32,872","$56,791"